### PR TITLE
Parse and render TTA type

### LINKED ISSUE #164: TTA type is not available
The document [ISO/TTA 2:1997](https://www.iso.org/standard/27598.html) has a type that this gem doesn't recognize.
```ruby
> Pubid::Iso::Identifier.parse_from_title("ISO/TTA 2:1997 Tensile tests for discontinuously reinforced metal matrix composites at ambient temperatures")
Pubid::Iso::Errors::WrongTypeError: TTA type is not available
from /Users/andrej/.rvm/gems/ruby-3.0.0/gems/pubid-iso-0.3.1/lib/pubid/iso/type.rb:53:in `initialize'
```

### PR DESCRIPTION
**Pull request by mico**
fixes #164

### CODE REVIEW

File: lib/pubid/iso/identifier/technology_trends_assessments.rb [hunk 1]
```diff
@@ -0,0 +1,28 @@
+module Pubid::Iso
+  module Identifier
+    class TechnologyTrendsAssessments < Base
+      def_delegators 'Pubid::Iso::Identifier::TechnologyTrendsAssessments', :type
+
+      TYPED_STAGES = {
+        dts: {
```
Comment (ronaldtse) [inline lib/pubid/iso/identifier/technology_trends_assessments.rb:7]: There is something wrong here: how can `:dts` represent a TTA?

Where are the other stages?

**Review by ronaldtse — CHANGES_REQUESTED** [review]

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
@mico can you please help rebase this? Thanks!
