### PR TITLE
Remove urn_stage that we are not using anymore

### LINKED ISSUE #129: URN needs to use urn_stage fully
This is a bug.

`Pubid::Iso::Identifier.new(number: 200, stage: "CD", urn_stage: "30.20").urn`  = `"urn:iso:std:iso:200:stage-30.00"`

This is incorrect: it is supposed to be "urn:iso:std:iso:200:stage-30.20". That is in fact the point of passing the urn_stage to the identifier. The urn values take priority over the stage value, especially as the stage value does not include the substage.

### PR DESCRIPTION
**Pull request by mico**
closes #129

### CODE REVIEW

File: spec/pubid_iso/identifier/create_new_identifier_spec.rb [hunk 1]
```diff
@@ -71,6 +71,18 @@ module Pubid::Iso
               .to eq(Pubid::Iso::HarmonizedStageCode.new("40", "60"))
           end
         end
+
+        context "when have harmonized code and abbr" do
+          let(:stage) { Stage.new(harmonized_code: "50.00", abbr: :PRF) }
```
Comment (ronaldtse) [inline spec/pubid_iso/identifier/create_new_identifier_spec.rb:76]: Can we also add an example for `harmonized_code: "50.00", abbr: :FDIS`?

**Review by ronaldtse — CHANGES_REQUESTED** [review]

File: spec/pubid_iso/identifier/create_new_identifier_spec.rb (hunk 1 above)
Comment (ronaldtse) [reply spec/pubid_iso/identifier/create_new_identifier_spec.rb:76]: Ping

Comment (ronaldtse) [reply spec/pubid_iso/identifier/create_new_identifier_spec.rb]: I added the test in 0a6b936

**Review by ronaldtse — APPROVED** [review]
