### PR TITLE
Supplement stage fix

### LINKED ISSUE #193: Broken rendering for typed stage in Amendments that are Published or in PRF
````
base = Pubid::Iso::Identifier.parse("ISO 17301-1:2016")
base.edition = 1
id = Pubid::Iso::Identifier.create(:number=>"1", :type=>:amd, :publisher=>"ISO", :year=>"2017", :iteration=>"3", :stage=>"60.60", :base=>base)

id.to_s = "ISO 17301-1:2016/#<Pubid::Core::Stage:0x0000000106f67e10>Amd 1.3:2017"
````

Same behaviour if stage is "50.00".

### PR DESCRIPTION
**Pull request by mico**
closes #193 

Part of the fix in updated pubid-core: https://github.com/metanorma/pubid-core/releases/tag/v1.5.1

### CODE REVIEW

File: spec/pubid_iso/identifier/amendment_spec.rb [hunk 1]
```diff
@@ -92,6 +92,24 @@ module Identifier
...
+          context "when stage is a harmonized code" do
+            context "when stage is 50.00" do
+              let(:stage) { "50.00" }
+
+              it "renders long stage and amendment" do
+                expect(subject.to_s).to eq("ISO #{number}:1999/FDAM 1")
+              end
+            end
+
+            context "when stage is 60.60" do
```
Comment (ronaldtse) [inline spec/pubid_iso/identifier/amendment_spec.rb:105]: @mico can you add a test for "60.00"? The result should also be `ISO #{number{:1999}/Amd 1`.

**Review by ronaldtse — APPROVED** [review]
